# Brightness
bindsym XF86MonBrightnessUp exec light -A 10
bindsym XF86MonBrightnessDown exec light -U 10

# Media
bindsym XF86AudioPrev exec playerctl previous
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPlay exec playerctl play-pause

# Volume
bindsym XF86AudioRaiseVolume exec $HOME/.dotfiles/Files/Linux/sway/scripts/volume.sh +
bindsym XF86AudioLowerVolume exec $HOME/.dotfiles/Files/Linux/sway/scripts/volume.sh -
bindsym XF86AudioMute exec $HOME/.dotfiles/Files/Linux/sway/scripts/volume.sh x